IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES
      WHERE TABLE_NAME = 'T1')
   DROP TABLE T1
GO
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.VIEWS
      WHERE TABLE_NAME = 'V1')
   DROP VIEW V1
GO

CREATE TABLE T1 ( column_1 int, column_2 varchar(30))


CREATE VIEW V1 -- WITH ENCRYPTION(optional)
AS 
 SELECT column_2, column_1 
 FROM T1


INSERT INTO V1 VALUES ('Row 1',1)
SELECT * FROM T1

